### ISSUE TITLE
[Enhancement] Remove User, change group pfps, send msg to groups

### ISSUE THREAD

**Issue by 9qz** [FuckingToasters/discord-group-spammer#1]
remove user
change all server pfps (imma make that looks simple enough)
send message to all groups

**Comment by FuckingToasters** [comment]
> remove user change all server pfps (imma make that looks simple enough) send message to all groups

This is a good suggestion. However there are some issues with a few suggested options:

__remove user__
Do you mean a single user in all groups or every user in every group? The second one is a bit harder because you would need to fetch all userids what is defently against discord tos.
Another option could be, to save the userids right after adding and then using the stored userids to remove them. this would be more simple, is not a big api abuse and we can count that as educational :)

__change all server pfps__
Sounds good however i think you meant group pictures. i will add that later

__send message to all groups__
i also can do this later => when i am at home.

**Comment by 9qz** [comment]
oh and also you should add transfer groups
and no only one user just like adding you paste the id of the one user but instead you remove the user

**Comment by FuckingToasters** [comment]
Hi there!
I worked a bit on the code, deleted the previous files but kept the namechanging file.
All deleted files have been merged to 1 big file including the send message to all groups and change group icon functionallity.
removing a user i will surely add later and the single name changer file is not converted to the all_together.py yet.

**Comment by 9qz** [comment]
hey! you can easily remove a user with requests.delete instead of requests.put

**Comment by FuckingToasters** [comment]
> hey! you can easily remove a user with requests.delete instead of requests.put

I am aware of this. I might include a selectable option like the one for adding, making a group etc for other actions you can do like removing a user using requests.delete and so on.

**Comment by 9qz** [comment]
you should fix the name on all_of_it.py by printing 1 by 1 instead of all of it

**Comment by FuckingToasters** [comment]
> you should fix the name on all_of_it.py by printing 1 by 1 instead of all of it

Could you give a better explatation what you want me to solve? I did not really understood what you meant.

**Comment by 9qz** [comment]
basically when you print the ascii stuff you should print it line by line it should fix being out of place

**Comment by FuckingToasters** [comment]
Hmm i still don't know what exactly you meant. Maybe it helps to give a example.

**Comment by FuckingToasters** [comment]
> basically when you print the ascii stuff you should print it line by line it should fix being out of place

Hmm i still dont get it. Do you have a example or can it describe a bit better?

**Comment by 9qz** [comment]
![image](https://user-images.githubusercontent.com/82518573/142759775-21a2aac7-0dff-4f1a-b65e-4591df14d02e.png)
you should print this text one by one and this wouldnt happen anymore

**Comment by FuckingToasters** [comment]
Yea  that is because the text is too large. you can maxe cmd bigger or fullscreen and then it will show correctly however it defently is not only a joiner anymore so i changed the text to "Discord Tools" in the next code i will push and this text then also should fit in the small cmd window and should show correctly. i also tried to do a single print line for each like of the acii art but the result where the same you sent on the screenshot. Now there are 6 different options included:

- Mass Group Creator
- Mass Member to Group Adder
- Mass Group Name Changer
- Mass Group Icon Changer
- Mass Group Message Sender
- Mass Guildmembers Fetecher

**Comment by 9qz** [comment]
change all group pfps is broken it only changes 1 group forever

**Comment by FuckingToasters** [comment]
> change all group pfps is broken it only changes 1 group forever

I will solve all issues on the next weekend. At the Moment i work on a fix to the issue, that it prints a member got added to a group even tho the member is not added .This happen because it do the same requests multiplie times and i hope, i get this fixed.
